"""initial migration

Revision ID: 6d5e34989c2d
Revises: 
Create Date: 2021-04-07 23:07:58.515490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5e34989c2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    op.drop_table('navigation')
    op.alter_column('article_comments', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('article_comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'article_comments', type_='foreignkey')
    op.drop_constraint(None, 'article_comments', type_='foreignkey')
    op.create_foreign_key(None, 'article_comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'article_comments', 'articles', ['article_id'], ['id'])
    op.add_column('forum_comments', sa.Column('forum_id', sa.Integer(), nullable=True))
    op.alter_column('forum_comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'forum_comments', type_='foreignkey')
    op.drop_constraint(None, 'forum_comments', type_='foreignkey')
    op.create_foreign_key(None, 'forum_comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'forum_comments', 'articles', ['forum_id'], ['id'])
    op.drop_column('forum_comments', 'article_id')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.add_column('forum_comments', sa.Column('article_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'forum_comments', type_='foreignkey')
    op.drop_constraint(None, 'forum_comments', type_='foreignkey')
    op.create_foreign_key(None, 'forum_comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'forum_comments', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
    op.alter_column('forum_comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('forum_comments', 'forum_id')
    op.drop_constraint(None, 'article_comments', type_='foreignkey')
    op.drop_constraint(None, 'article_comments', type_='foreignkey')
    op.create_foreign_key(None, 'article_comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'article_comments', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
    op.alter_column('article_comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('article_comments', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('navigation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
