# Generated by Django 3.0.8 on 2020-07-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlemodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenuElementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=20)),
            ],
        ),
    ]
