# Generated by Django 3.0.8 on 2020-07-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_mainmenuelementmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
