# Generated by Django 3.0.8 on 2020-08-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_commentmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterShitContentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
                ('ref', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FooterShitBlockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footerShitContent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.FooterShitContentModel')),
            ],
        ),
    ]
