# Generated by Django 3.0.8 on 2020-08-09 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_footershitblockmodel_footershitcontentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBlockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FooterContentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
                ('ref', models.CharField(max_length=30)),
                ('footerBlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.FooterBlockModel')),
            ],
        ),
        migrations.DeleteModel(
            name='FooterShitBlockModel',
        ),
        migrations.DeleteModel(
            name='FooterShitContentModel',
        ),
    ]
