# Generated by Django 3.0.8 on 2020-08-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200809_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerblockmodel',
            name='name',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
