# Generated by Django 3.0.8 on 2020-08-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_footerblockmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerblockmodel',
            name='name',
            field=models.CharField(default='defaultName', max_length=20),
        ),
    ]
