# Generated by Django 3.0.8 on 2020-08-09 18:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
