# Generated by Django 3.0.8 on 2020-08-10 09:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200809_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
