# Generated by Django 3.0.8 on 2020-08-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20200810_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'verbose_name_plural': 'Cтатья'},
        ),
    ]
