# Generated by Django 3.1 on 2020-08-12 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20200810_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Other', max_length=20)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'verbose_name': 'Cтатья', 'verbose_name_plural': 'Cтатьи'},
        ),
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='footerblockmodel',
            options={'verbose_name': 'Блок в футере', 'verbose_name_plural': 'Блоки в футере'},
        ),
        migrations.AlterModelOptions(
            name='footercontentmodel',
            options={'verbose_name': 'Элемент блока в футере', 'verbose_name_plural': 'Элементы блока в футере'},
        ),
        migrations.AlterModelOptions(
            name='mainmenuelementmodel',
            options={'verbose_name': 'Элемент навигации хедера', 'verbose_name_plural': 'Элементы навигации хедера'},
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.categorymodel'),
        ),
    ]
