# Generated by Django 3.1 on 2020-08-13 08:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_articletagmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Одиночные статьи',
                'verbose_name_plural': 'Одиночные статьи',
            },
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(default='Other', max_length=20),
        ),
    ]
